### ISSUE TITLE
Exemple

### ISSUE THREAD

**Issue by Goule** [almahdi/ra-data-parse#1]
Hello,

I'm new in web development and I can't find how to map my classes (which are in my parse REST API) with react admin thought this data provider. Can you provide an exemple (for exemple in the readme) to fetch, read and edit classes from Parse ? 

Thanks

**Comment by almahdi** [comment]
Using the resource provided by React-Admin

`
<Resource name="class_name" list={ListGuesser} show={ShowGuesser} />
`

Class names in Parse are case sensitive.
