### ISSUE TITLE
Which component I should use for the column like Post.className

### ISSUE THREAD

**Issue by zhouhao27** [almahdi/ra-data-parse#3]
I have a object called **Post** and an object called **Comment** in parse database. **Comment** have a reference field call **Post** point to **Post** object. I use ListGuesser :

`<Resource name="Comment" list={ListGuesser} />`

Got this in browser console:

```
export const CommentList = props => (
    <List {...props}>
        <Datagrid rowClick="edit">
            <TextField source="id" />
            <DateField source="createdAt" />
            <DateField source="updatedAt" />
            <TextField source="content" />
            <NumberField source="likes" />
            <TextField source="owner" />
            <TextField source="post.className" />
        </Datagrid>
    </List>
);
```

It shows the **post** field in **Comment** as a **TextField**. Apparently it's not true. How can I get the reference object and show a link? Thanks.

**Comment by almahdi** [comment]
if you create a codesandbox with your code I can help you modify it. The guesser functions cannot always guess relations.

**Comment by almahdi** [comment]
Since there is no response for a long time, I'm closing this issue.
